In [ ]:
#____________________________________________task___________________________________________________

In [ ]:
import pandas as pd
df={
    
        'name':['harshit','hari','rahul','riya'],
        'age':[22,23,24,21],
        'exp':[1,2,3,4],
        'post':["clerk","clerk","cashier","hr"],
        'salary':[20000,25000,30000,35000]

    }

d=pd.DataFrame(df)
#d.iloc[:,0]#(only fethched coloumn at zero index)
#d.iloc[:,[1,4]]#(fetched first and fourth coloumn)
#d.iloc[[1,3]#(fetches the all values of 1 and 3)
#d.iloc[1,[0,2]]#(FETCHES THE  1 VALUE FROM THE 0 AND 2 COLOUMN)


d[d["age"]>=22].iloc[:,:]#(FETHES THE CONDITION APPLIED ON ALL COLOUMNS AND ALL ROWS )

In [ ]:
#______________________________________________assignment1____________________________________________

In [ ]:
import pandas as pd
d=pd.DataFrame(
    {
        "emp_id":[101,102,103,104,105],
        "name":['rahul',"anita","amit","neha","rohit"],
        "department":["it",'hr',"it","finance","hr"],
        "salary":[50000,45000,60000,55000,48000],
        "experience":[2,3,5,4,2]
    }
)
# print(d,"\n")
# q=d.iloc[:,[1,3]]
# print(q,"\n")
# w=d.iloc[0:3]
# print(w,'\n')
# e=d[d["department"]=="it"]
# print(e,"\n")
# r=d[d["salary"]>50000]
# print(r,"\n")
# d["bonus"]=d.loc[(d["experience"]>0),"salary"]*0.10
# print(d)
# y=d.agg({"name",["salary"]:"max"})
# print(y)
# u=d.sort_values(by=["salary"],ascending=True)
# print(u)
# d["new_salary"]=d.loc[(d["experience"]>=3),"salary"]+5000
# print(d)
# i=d["department"].value_counts()
# print(i)
o=d.rename(
    columns={
        "salary":"paycheck"
    }
)
print(o)

In [ ]:
#__________________________________________assignment2____________________________________________

SERIES BASICS

In [6]:
#(1)
import pandas as pd
import numpy as np
l=[10,20,30,40,50]
df=pd.Series(np.array(l))
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
#(2)
import pandas as pd
import numpy as np
l=[10,20,30,40,50]
df=pd.Series(np.array(l),index=["a","b","c","d","e"])
df

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [14]:
#(3)
import pandas as pd
import numpy as np
l=[10,20,30,40,50]
df=pd.Series(np.array(l),index=["a","b","c","d","e"])
d=df[2]
d

C:\Users\TECHCADD\AppData\Local\Temp\ipykernel_5584\2104461109.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d=df[2]

np.int64(30)

In [18]:
#(4)
import pandas as pd
import numpy as np
l=[10,20,30,40,50]
df=pd.Series(np.array(l),index=["a","b","c","d","e"])
df["c"]="100" #or df[2]="100"
df

C:\Users\TECHCADD\AppData\Local\Temp\ipykernel_5584\226586627.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '100' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df["c"]="100" #or df[2]="100"

a     10
b     20
c    100
d     40
e     50
dtype: object

In [ ]:
#(5)
import pandas as pd
import numpy as np
l=[10,20,30,40,50]
df=pd.Series(np.array(l),index=["a","b","c","d","e"])
df.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

DATA FRAME CREATION AND VIEWING

In [ ]:
data={
    "name":["amit","priya","rahul","sneha"],
    "age":[23,25,22,24],
    "city":["delhi",'mumbai',"pune","chennai"]

}
d=pd.DataFrame(data)
d

    name  age     city
0   amit   23    delhi
1  priya   25   mumbai
2  rahul   22     pune
3  sneha   24  chennai

In [21]:
#(6)
d[0:2:]

    name  age    city
0   amit   23   delhi
1  priya   25  mumbai

In [23]:
#(7)
d.columns

Index(['name', 'age', 'city'], dtype='object')

In [ ]:
#(8)
d["score"]=d["score"]=(1,2,3,4)
d

    name  age     city  score
0   amit   23    delhi      1
1  priya   25   mumbai      2
2  rahul   22     pune      3
3  sneha   24  chennai      4

DATAFRAME INDEXING AND SELECTION

In [26]:
data={
    "name":["amit","priya","rahul","sneha"],
    "age":[23,25,22,24],
    "city":["delhi",'mumbai',"pune","chennai"]

}
d=pd.DataFrame(data)
d

    name  age     city
0   amit   23    delhi
1  priya   25   mumbai
2  rahul   22     pune
3  sneha   24  chennai

In [28]:
#(9)
d.iloc[:,[0,2]]

    name     city
0   amit    delhi
1  priya   mumbai
2  rahul     pune
3  sneha  chennai

In [ ]:
#(10)
d.iloc[0:2,:]

    name  age    city
0   amit   23   delhi
1  priya   25  mumbai

In [32]:
#(11)
d[d["age"]>23]

    name  age     city
1  priya   25   mumbai
3  sneha   24  chennai

In [41]:
data={
    "name":["amit","priya","rahul","sneha"],
    "age":[23,25,22,24],
    "city":["delhi",'mumbai',"pune","chennai"]

}
d=pd.DataFrame(data)
d

    name  age     city
0   amit   23    delhi
1  priya   25   mumbai
2  rahul   22     pune
3  sneha   24  chennai

In [ ]:
#(12)
d.loc[d['name']=='rahul','city']="banglore"
d

    name  age      city
0   amit   23     delhi
1  priya   25    mumbai
2  rahul   22  banglore
3  sneha   24   chennai

In [45]:
d=pd.read_csv(r"c:\Users\TECHCADD\Downloads\employee_salary_dataset.csv")
d

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [57]:
#(13)
d.groupby('Department')[['Monthly_Salary']].mean()

            Monthly_Salary
Department
Finance       67261.900000
HR            82945.142857
IT            76520.500000
Marketing     96430.846154
Operations    84239.900000

In [59]:
#(14)
d.groupby("Department")[["Monthly_Salary"]].agg(["min","max","mean"])

           Monthly_Salary
                      min     max          mean
Department
Finance             28420  118179  67261.900000
HR                  43589  134616  82945.142857
IT                  30600  130983  76520.500000
Marketing           30895  141381  96430.846154
Operations          31893  149123  84239.900000

In [ ]:
#(15)
d["bonus"]=d.loc[:,"Monthly_Salary"]*0.10
d

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,bonus
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,11141.6
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,9527.1
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,6906.4
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,9509.1
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,13245.0
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818,6581.8
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525,7052.5
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830,4483.0
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429,4242.9
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893,3189.3
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381,14138.1
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909,10490.9
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333,7233.3
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436,2843.6
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290,9929.0
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213,10121.3
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895,3089.5
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738,4473.8
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746,5574.6
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377,7437.7
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404,7340.4
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045,7904.5
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888,12288.8
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790,6479.0
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455,13245.5
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600,3060.0
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660,11966.0
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179,11817.9
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764,6576.4
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543,9954.3
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714,7071.4
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835,8183.5
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946,12794.6
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616,13461.6
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983,13098.3
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744,9874.4
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491,8149.1
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123,14912.3
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589,4358.9
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484,6848.4
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989,10798.9
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212,6121.2
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525,6852.5
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202,7220.2
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635,5763.5
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208,8820.8
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828,5882.8
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711,4371.1
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420,2842.0
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752,12175.2

In [ ]:
#(16)
import pandas as pd
df={
    
        'name':['harshit','hari','rahul','riya'],
        'age':[22,23,24,21],
        'e_id':[1,2,3,4],
       

    }

d=pd.DataFrame(df)

df1={

        "company":["google","infosys",'excel',"techadd"],
        "e_id":[6,8,2,1],
        'salary':[20000,25000,30000,35000],

}

f=pd.DataFrame(df1)

h=pd.merge(d,f,on="e_id",how="inner")
h

      name  age  e_id  company  salary
0  harshit   22     1  techadd   35000
1     hari   23     2    excel   30000

In [ ]:
#(17)
import pandas as pd
df={
    
        'name':['harshit','hari','rahul','riya'],
        'age':[22,23,24,21],
        'exp':[1,2,3,4],
       

    }

d=pd.DataFrame(df)

df1={

        "company":["google","infosys",'excel',"techadd"],
        'post':["clerk","clerk","cashier","hr"],
        'salary':[20000,25000,30000,35000],

}

f=pd.DataFrame(df1)



pd.concat([d,f],axis=1)

      name  age  exp  company     post  salary
0  harshit   22    1   google    clerk   20000
1     hari   23    2  infosys    clerk   25000
2    rahul   24    3    excel  cashier   30000
3     riya   21    4  techadd       hr   35000

In [72]:
d=pd.read_csv(r"c:\Users\TECHCADD\Downloads\employee_salary_dataset.csv")
d

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [75]:
#(18)
print(d.loc[:,['Name','Department',"Monthly_Salary"]])

           Name  Department  Monthly_Salary
0    Employee_1   Marketing          111416
1    Employee_2  Operations           95271
2    Employee_3          IT           69064
3    Employee_4  Operations           95091
4    Employee_5  Operations          132450
5    Employee_6     Finance           65818
6    Employee_7          IT           70525
7    Employee_8          IT           44830
8    Employee_9          IT           42429
9   Employee_10  Operations           31893
10  Employee_11   Marketing          141381
11  Employee_12          IT          104909
12  Employee_13  Operations           72333
13  Employee_14     Finance           28436
14  Employee_15   Marketing           99290
15  Employee_16     Finance          101213
16  Employee_17   Marketing           30895
17  Employee_18  Operations           44738
18  Employee_19          HR           55746
19  Employee_20   Marketing           74377
20  Employee_21     Finance           73404
21  Employee_22  Operations           79045
22  Employee_23   Marketing          122888
23  Employee_24          HR           64790
24  Employee_25          HR          132455
25  Employee_26          IT           30600
26  Employee_27          IT          119660
27  Employee_28     Finance          118179
28  Employee_29   Marketing           65764
29  Employee_30   Marketing           99543
30  Employee_31          IT           70714
31  Employee_32   Marketing           81835
32  Employee_33   Marketing          127946
33  Employee_34          HR          134616
34  Employee_35          IT          130983
35  Employee_36  Operations           98744
36  Employee_37          IT           81491
37  Employee_38  Operations          149123
38  Employee_39          HR           43589
39  Employee_40     Finance           68484
40  Employee_41   Marketing          107989
41  Employee_42          HR           61212
42  Employee_43   Marketing           68525
43  Employee_44     Finance           72202
44  Employee_45     Finance           57635
45  Employee_46          HR           88208
46  Employee_47     Finance           58828
47  Employee_48  Operations           43711
48  Employee_49     Finance           28420
49  Employee_50   Marketing          121752

In [ ]:
#(19)
d["City"].unique()

array(['Delhi', 'Bangalore', 'Hyderabad', 'Mumbai', 'Chennai'],
      dtype=object)

In [2]:
import pandas as pd 
data={
    "name":["amit","priya","rahul","sneha"],
    "age":[23,25,22,24],
    "city":["delhi",'mumbai',"pune","chennai"]

}
d=pd.DataFrame(data)
d

    name  age     city
0   amit   23    delhi
1  priya   25   mumbai
2  rahul   22     pune
3  sneha   24  chennai

In [ ]:
d["age"]=d["age",(dtype=="int")]

NameError: name 'dtype' is not defined